apiVersion: v1
kind: ConfigMap
metadata:
  name: nextosp-config
  namespace: nextosp
data:
  nwos.conf: |
    [options]
    addons_path = /opt/nwos/addons,/opt/nwos/nwos/addons
    data_dir = /var/lib/nwos
    db_host = nextosp-postgres
    db_port = 5432
    db_user = nwos
    db_name = nwos
    http_interface = 0.0.0.0
    http_port = 7073
    gevent_port = 8072
    log_level = info
    proxy_mode = True
    workers = 4
    max_cron_threads = 0
    db_maxconn = 64
    limit_memory_soft = 2147483648
    limit_memory_hard = 2684354560
    limit_time_cpu = 60
    limit_time_real = 120
