[options]
addons_path = /opt/nwos/addons,/opt/nwos/nwos/addons
data_dir = /var/lib/nwos
db_host = db
db_port = 5432
db_user = nwos
db_password = nwos
db_name = False
http_interface = 0.0.0.0
http_port = 7073
log_level = info
proxy_mode = True
workers = 2
max_cron_threads = 1
