import base64

from nwos import SUPERUSER_ID, api, tools


OLD_DEFAULT_FAVICON = (
    b"AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABMLAAATCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhIcCBmS3CgZkxwz2dLcf9nS3H/Z0tx32hMcIBwQHAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGlLcHBmS3HvZ0tx/2dLcf9nS3H/Z0tx/2dLcf9nS3H/Zktx72hNcGAAAAAAAAAAAAAAAAAAAAAAAAAAAGhKcGBnS3H/Z0tx/2dLcf9nS3H/Zktx72ZLce9nS3H/Z0tx/2dLcf9nS3H/ZktwcAAAAAAAAAAAAAAAAGBQcBBmS3HvZ0tx/2dLcf9nS3G/ZUpwMAAAAAAAAAAAZExwQGdLcb9nS3H/Z0tx/2ZLce9oSHAgAAAAAAAAAABoTHCAZ0tx/2dLcf9nS3G/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ0txv2dLcf9nS3H/Z0twnwAAAAAAAAAAZ0tx32dLcf9nS3H/ZEx0QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGpQcDBnS3H/Z0tx/2ZKcc8AAAAAAAAAAGdLcf9nS3H/Z0tx7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZktx72dLcf9nS3H/AAAAAAAAAABnS3H/Z0tx/2dLce8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZLce9nS3H/Z0tx/wAAAAAAAAAAZkxxz2dLcf9nS3H/akpwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhMcEBnS3H/Z0tx/2dLcd8AAAAAAAAAAGZLcaBnS3H/Z0tx/2dMcL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnS3G/Z0tx/2dLcf9mTHKAAAAAAAAAAABoUHAgZktx72dLcf9nS3H/Z0xwv2hMcEAAAAAAAAAAAGVKcDBnS3G/Z0tx/2dLcf9nS3HvcEBwEAAAAAAAAAAAAAAAAGdMcW9nS3H/Z0tx/2dLcf9nS3H/Zktx72ZLce9nS3H/Z0tx/2dLcf9nS3H/aUtxXwAAAAAAAAAAAAAAAAAAAAAAAAAAaUtxX2ZLce9nS3H/Z0tx/2dLcf9nS3H/Z0tx/2dLcf9nS3HvZklwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwUHAQZkpyf2dKcd9nS3H/Z0tx/2dLcc9nS3KfaFBwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAPAPAADgBwAAwAMAAIGBAACH4QAAh+EAAI/xAACP8QAAh+EAAIfhAACBgQAAwAMAAOAHAADwDwAA//8AAA=="
)


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})
    with tools.file_open("web/static/img/favicon.ico", "rb") as favicon:
        new_default_favicon = base64.b64encode(favicon.read())

    old_default_favicon = OLD_DEFAULT_FAVICON.decode()
    websites = env["website"].search([])
    for website in websites:
        if website.favicon in (OLD_DEFAULT_FAVICON, old_default_favicon):
            website.favicon = new_default_favicon
