#!/bin/sh

set -e

NWOS_CONFIGURATION_FILE=/etc/nwos/nwos.conf
NWOS_GROUP="nwos"
NWOS_DATA_DIR=/var/lib/nwos
NWOS_LOG_DIR=/var/log/nwos
NWOS_USER="nwos"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^nwos:"; then
            adduser --system --home $NWOS_DATA_DIR --quiet --group $NWOS_USER
            # Data dir
            chown $NWOS_USER:$NWOS_GROUP $NWOS_DATA_DIR
        fi
        # Register "$NWOS_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $NWOS_USER" 2> /dev/null || true
        # Configuration file
        chown $NWOS_USER:$NWOS_GROUP $NWOS_CONFIGURATION_FILE
        chmod 0640 $NWOS_CONFIGURATION_FILE
        # Log
        mkdir -p $NWOS_LOG_DIR
        chown $NWOS_USER:$NWOS_GROUP $NWOS_LOG_DIR
        chmod 0750 $NWOS_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-nwos-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
